projectCD/appgege/urls.py
from django.urls import re_path
from .views import TableTennis, StatusHTML
#url for app
urlpatterns = [
    re_path(r'^$', TableTennis, name='table'),
    re_path('table', StatusHTML, name = 'status') 
]

projectCD/projectCD/urls.py
from django.contrib import admin
from django.urls import re_path
from appgege.views import TableTennis, StatusHTML
from django.conf.urls import url, include
urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('', include(('appgege.urls','status'), namespace = 'appgege')),
]

projectCD/appgege/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Table(models.Model):
    date = models.DateTimeField(default = datetime.now)
    box = models.CharField(max_length=300)

projectCD/appgege/forms.py
from django import forms
from .models import Table
from datetime import datetime

class FormTable(forms.ModelForm):
    box = forms.CharField(widget=forms.TextInput(attrs={'type':'text'}),required=True)

    class Meta:
        model = Table
        fields = ('box',)

projectCD/appgege/views.py
from django.shortcuts import render
from .models import Table
from .forms import *
# Create your views here.

def TableTennis(request):
    if (request.method == "POST"):
        form = FormTable(request.POST or None)
        if form.is_valid():
            print(request.POST)
            box = request.POST["box"]
            post = Table(box=box)
            post.save()
    else:
        
        form = FormTable()
    all_table = Table.objects.all()
    print(all_table)
    return render(request, 'StatusHTML.html', {'Table': all_table,'form':form})

def StatusHTML(request):
    all_table = Table.objects.all()
    html = 'StatusHTML.html'
    print(all_table)
    return render(request, html, {'Table':all_table})

projectCD/appgege/templates/StatusHTML.html
<html>
{% load staticfiles %}
    <head>

    </head>

    <body>
        <div class="container">
            <h1> Halo, apa kabar? </h1>
            
            <form action="{% url 'appgege:table' %}" method="post">
            
            {% csrf_token %}
            <div>{{ form }}</div><br>           
            
            <button class="bt1" type="submit" value="submit">Submit</button>
            
            
        {% for tio in Table %}
        <p> {{tio.date}}</p>
        <p> {{tio.box}}</p>

        
        {% endfor %}
            
        
        
        
        
        </div>
    
    </body>



































</html>